package com.mobile.massiveapp.domain.model

import com.mobile.massiveapp.data.database.entities.ClienteFacturasEntity
import com.mobile.massiveapp.data.model.ClienteFacturas

data class DoClienteFacturas (
    val Address: String,
    val Address2: String,
    val CardCode: String,
    val CardName: String,
    val Comments: String,
    val DocCur: String,
    val DocDate: String,
    val DocDueDate: String,
    var DocEntry: Int,
    val DocNum: Int,
    val DocRate: Double,
    val DocStatus: String,
    val DocTotal: Double,
    val FolioNum: String,
    val FolioPref: String,
    val GroupNum: Int,
    val Indicator: String,
    val InstlmntID: Int,
    val LicTradNum: String,
    val NumAtCard: String,
    val PaidToDate: Double,
    val PayToCode: String,
    val ShipToCode: String,
    val SlpCode: Int,
    val TaxDate: String,
    var Edit_Ptd: Double,
    val Zona: String
) {
    constructor():this(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        0,
        0,
        0.0,
        "",
        0.0,
        "0",
        "",
        0,
        "",
        0,
        "",
        "",
        0.0,
        "",
        "",
        0,
        "",
        0.0,
        ""
    )
}

fun ClienteFacturasEntity.toDomain() = DoClienteFacturas(
    Address = Address,
    Address2 = Address2,
    CardCode = CardCode,
    CardName = CardName,
    Comments = Comments,
    DocCur = DocCur,
    DocDate = DocDate,
    DocDueDate = DocDueDate,
    DocEntry = DocEntry,
    DocNum = DocNum,
    DocRate = DocRate,
    DocStatus = DocStatus,
    DocTotal = DocTotal,
    FolioNum = FolioNum.toString().padStart(8, '0'),
    FolioPref = FolioPref,
    GroupNum = GroupNum,
    Indicator = Indicator,
    InstlmntID = InstlmntID,
    LicTradNum = LicTradNum,
    NumAtCard = NumAtCard,
    PaidToDate = PaidToDate,
    PayToCode = PayToCode,
    ShipToCode = ShipToCode,
    SlpCode = SlpCode,
    TaxDate = TaxDate,
    Edit_Ptd = Edit_Ptd,
    Zona = ""
)

fun ClienteFacturas.toDomain() = DoClienteFacturas(
    Address = Address,
    Address2 = Address2,
    CardCode = CardCode,
    CardName = CardName,
    Comments = Comments,
    DocCur = DocCur,
    DocDate = DocDate,
    DocDueDate = DocDueDate,
    DocEntry = DocEntry,
    DocNum = DocNum,
    DocRate = DocRate,
    DocStatus = DocStatus,
    DocTotal = DocTotal,
    FolioNum = FolioNum.toString().padStart(8, '0'),
    FolioPref = FolioPref,
    GroupNum = GroupNum,
    Indicator = Indicator,
    InstlmntID = InstlmntID,
    LicTradNum = LicTradNum,
    NumAtCard = NumAtCard,
    PaidToDate = PaidToDate,
    PayToCode = PayToCode,
    ShipToCode = ShipToCode,
    SlpCode = SlpCode,
    TaxDate = TaxDate,
    Edit_Ptd = 0.0,
    Zona = ""
)

fun DoClienteFacturas.toDatabase() = ClienteFacturasEntity(
    Address = Address,
    Address2 = Address2,
    CardCode = CardCode,
    CardName = CardName,
    Comments = Comments,
    DocCur = DocCur,
    DocDate = DocDate,
    DocDueDate = DocDueDate,
    DocEntry = DocEntry,
    DocNum = DocNum,
    DocRate = DocRate,
    DocStatus = DocStatus,
    DocTotal = DocTotal,
    FolioNum = FolioNum.toInt(),
    FolioPref = FolioPref,
    GroupNum = GroupNum,
    Indicator = Indicator,
    InstlmntID = InstlmntID,
    LicTradNum = LicTradNum,
    NumAtCard = NumAtCard,
    PaidToDate = PaidToDate,
    PayToCode = PayToCode,
    ShipToCode = ShipToCode,
    SlpCode = SlpCode,
    TaxDate = TaxDate,
    Edit_Ptd = Edit_Ptd,
    Zona = "03"
)

fun DoClienteFacturas.toModel() = ClienteFacturas(
    Address = Address,
    Address2 = Address2,
    CardCode = CardCode,
    CardName = CardName,
    Comments = Comments,
    DocCur = DocCur,
    DocDate = DocDate,
    DocDueDate = DocDueDate,
    DocEntry = DocEntry,
    DocNum = DocNum,
    DocRate = DocRate,
    DocStatus = DocStatus,
    DocTotal = DocTotal,
    FolioNum = FolioNum.toInt(),
    FolioPref = FolioPref,
    GroupNum = GroupNum,
    Indicator = Indicator,
    InstlmntID = InstlmntID,
    LicTradNum = LicTradNum,
    NumAtCard = NumAtCard,
    PaidToDate = PaidToDate,
    PayToCode = PayToCode,
    ShipToCode = ShipToCode,
    SlpCode = SlpCode,
    TaxDate = TaxDate,
    emptyList()
)

data class DoFacturaView(
    val CardName: String,
    val DocCur: String,
    var DocEntry: Int,
    val DocDate: String,
    val CardCode: String,
    val DocTotal: Double,
    val FolioNum: String,
    val FolioPref: String,
    val PaidToDate: Double,
    val Zona: String
)