package com.mobile.massiveapp.domain.model

import com.mobile.massiveapp.data.database.entities.ConsultaDocumentoEntity
import com.mobile.massiveapp.data.model.ConsultaDocumento
import com.mobile.massiveapp.data.model.ConsultaDocumentoDireccion

data class DoConsultaDocumento(
    val ActividadEconomica1: String,
    val ActividadEconomica2: String,
    val ActividadEconomica3: String,
    val Activo: String,
    val AgentePercepcion: String,
    val AgenteRetenedor: String,
    val ApellidoMaterno: String,
    val ApellidoPaterno: String,
    val BuenContribuyente: String,
    val Consulta: String,
    val Error: String,
    val Fecha: String,
    val Habido: String,
    val Habilitar: String,
    val Indicador: String,
    val NombreComercial: String,
    val NumeroDocumento: String,
    val PersonaNaturalConNegocio: String,
    val PrimerNombre: String,
    val RazonSocial: String,
    val SegundoNombre: String,
    val Telefono1: String,
    val Telefono2: String,
    val Telefono3: String,
    val TipoDocumento: String,
    val TipoPersona: String,
    val Nombre: String,

    val Calle: String,
    val PaisCodigo: String,
    val DepartamentoNombre: String,
    val DepartamentoCodigo: String,
    val ProvinciaNombre: String,
    val DistritoNombre: String,
    val CodigoPostal: String
){
    constructor(): this(
        ActividadEconomica1 = "",
        ActividadEconomica2 = "",
        ActividadEconomica3 = "",
        Activo = "",
        AgentePercepcion = "",
        AgenteRetenedor = "",
        ApellidoMaterno = "",
        ApellidoPaterno = "",
        BuenContribuyente = "",
        Consulta = "",
        Error = "",
        Fecha = "",
        Habido = "",
        Habilitar = "",
        Indicador = "",
        NombreComercial = "",
        NumeroDocumento = "",
        PersonaNaturalConNegocio = "",
        PrimerNombre = "",
        RazonSocial = "",
        SegundoNombre = "",
        Telefono1 = "",
        Telefono2 = "",
        Telefono3 = "",
        TipoDocumento = "",
        TipoPersona = "",
        Calle = "",
        DepartamentoNombre = "",
        ProvinciaNombre = "",
        DistritoNombre = "",
        Nombre = "",
        CodigoPostal = "",
        PaisCodigo = "",
        DepartamentoCodigo = ""
    )
}

fun ConsultaDocumento.toDomain(direccion: ConsultaDocumentoDireccion) = DoConsultaDocumento(
    ActividadEconomica1 = ActividadEconomica1?:"",
    ActividadEconomica2 = ActividadEconomica2?:"",
    ActividadEconomica3 = ActividadEconomica3?:"",
    Activo = Activo?:"",
    AgentePercepcion = AgentePercepcion?:"",
    AgenteRetenedor = AgenteRetenedor?:"",
    ApellidoMaterno = ApellidoMaterno?:"",
    ApellidoPaterno = ApellidoPaterno?:"",
    BuenContribuyente = BuenContribuyente?:"",
    Consulta = Consulta?:"",
    Error = Error?:"",
    Fecha = Fecha?:"",
    Habido = Habido?:"",
    Habilitar = Habilitar?:"",
    Indicador = Indicador?:"",
    NombreComercial = NombreComercial?:"",
    NumeroDocumento = NumeroDocumento?:"",
    PersonaNaturalConNegocio = PersonaNaturalConNegocio?:"",
    PrimerNombre = PrimerNombre?:"",
    RazonSocial = RazonSocial?:"",
    SegundoNombre = SegundoNombre?:"",
    Telefono1 = Telefono1?:"",
    Telefono2 = Telefono2?:"",
    Telefono3 = Telefono3?:"",
    TipoDocumento = TipoDocumento?:"",
    TipoPersona = TipoPersona?:"",
    Calle = direccion.Calle?:"",
    PaisCodigo = direccion.PaisCodigo?:"",
    DepartamentoNombre = direccion.DepartamentoNombre?:"",
    DepartamentoCodigo = direccion.DepartamentoCodigo?:"",
    ProvinciaNombre = direccion.ProvinciaNombre?:"",
    DistritoNombre = direccion.DistritoNombre?:"",
    CodigoPostal = direccion.CodigoPostal?:"",
    Nombre = "$PrimerNombre $SegundoNombre $ApellidoPaterno $ApellidoMaterno"
)

fun ConsultaDocumentoEntity.toDomain(direccion: ConsultaDocumentoDireccion) = DoConsultaDocumento(
    ActividadEconomica1 = ActividadEconomica1,
    ActividadEconomica2 = ActividadEconomica2,
    ActividadEconomica3 = ActividadEconomica3,
    Activo = Activo,
    AgentePercepcion = AgentePercepcion,
    AgenteRetenedor = AgenteRetenedor,
    ApellidoMaterno = ApellidoMaterno,
    ApellidoPaterno = ApellidoPaterno,
    BuenContribuyente = BuenContribuyente,
    Consulta = Consulta,
    Error = Error,
    Fecha = Fecha,
    Habido = Habido,
    Habilitar = Habilitar,
    Indicador = Indicador,
    NombreComercial = NombreComercial,
    NumeroDocumento = NumeroDocumento,
    PersonaNaturalConNegocio = PersonaNaturalConNegocio,
    PrimerNombre = PrimerNombre,
    RazonSocial = RazonSocial,
    SegundoNombre = SegundoNombre,
    Telefono1 = Telefono1,
    Telefono2 = Telefono2,
    Telefono3 = Telefono3,
    TipoDocumento = TipoDocumento,
    TipoPersona = TipoPersona,
    Calle = direccion.Calle?:"",
    PaisCodigo = direccion.PaisCodigo?:"",
    DepartamentoNombre = direccion.DepartamentoNombre?:"",
    DepartamentoCodigo = direccion.DepartamentoCodigo?:"",
    ProvinciaNombre = direccion.ProvinciaNombre?:"",
    DistritoNombre = direccion.DistritoNombre?:"",
    CodigoPostal = direccion.CodigoPostal?:"",
    Nombre = "$PrimerNombre $SegundoNombre $ApellidoPaterno $ApellidoMaterno"
)
