package com.mobile.massiveapp.domain.model

data class DoConfigurarUsuarioInfo (
    val Code: String,
    val Password: String,
    val IdPhone1: String,

    val Name: String,
    val Email: String,
    val Phone1: String,

    val DefaultSlpCode: String,
    val NombreVendedor: String,

    val DefaultOrderSeries: String,
    val DefaultPagoRSeries: String,
    val DefaultSNSerieCli: String,
    val DefaultPriceList: String,
    val DefaultWarehouse: String,
    val DefaultCurrency: String,
    val DefaultTaxCode: String,
    val DefaultProyecto: String,
    val DefaultConductor: String,
    val DefaultZona: String,

    val SeriePedido: String,
    val SeriePago: String,
    val SerieSocio: String,
    val ListaPrecio: String,
    val Almacen: String,
    val Moneda: String,
    val Impuesto: String,
    val Proyecto: String,

    val DefaultAcctCodeCh: String,
    val DefaultAcctCodeDe: String,
    val DefaultAcctCodeEf: String,
    val DefaultAcctCodeTr: String,

    val CuentaCheque: String,
    val CuentaDeposito: String,
    val CuentaEfectivo: String,
    val CuentaTransferencia: String,

    val SuperUser: String,
    val AccLocked: String,
    val CanApprove: String,
    val CanCreate: String,
    val CanDecline: String,
    val CanEditPrice: String,
    val CanUpdate: String,
    val AccStatusSession: String
){
    constructor(): this(
        Code = "",
        Password = "",
        IdPhone1 = "",
        Name = "",
        Email = "",
        Phone1 = "",
        DefaultSlpCode = "",
        NombreVendedor = "",
        DefaultOrderSeries = "",
        DefaultPagoRSeries = "",
        DefaultSNSerieCli = "",
        DefaultPriceList = "",
        DefaultWarehouse = "",
        DefaultCurrency = "",
        DefaultTaxCode = "",
        DefaultProyecto = "",
        DefaultConductor = "",
        SeriePedido = "",
        SeriePago = "",
        SerieSocio = "",
        ListaPrecio = "",
        Almacen = "",
        Moneda = "",
        Impuesto = "",
        Proyecto = "",
        DefaultAcctCodeCh = "",
        DefaultAcctCodeDe = "",
        DefaultAcctCodeEf = "",
        DefaultAcctCodeTr = "",
        DefaultZona = "",
        CuentaCheque = "",
        CuentaDeposito = "",
        CuentaEfectivo = "",
        CuentaTransferencia = "",
        SuperUser = "",
        AccLocked = "",
        CanApprove = "",
        CanCreate = "",
        CanDecline = "",
        CanEditPrice = "",
        CanUpdate = "",
        AccStatusSession = ""
    )
}