package com.mobile.massiveapp.domain.model

import com.mobile.massiveapp.data.database.entities.UsuarioEntity
import com.mobile.massiveapp.data.model.Usuario

data class DoUsuario (
    val Code: String,
    val Comment: String,
    val DefaultCC1: String,
    val DefaultCC2: String,
    val DefaultCC3: String,
    val DefaultCC4: String,
    val DefaultCC5: String,
    val DefaultCurrency: String,
    val DefaultEmpId: Int,
    val DefaultAcctCodeEf: String,
    val DefaultAcctCodeTr: String,
    val DefaultAcctCodeCh: String,
    val DefaultAcctCodeDe: String,
    val DefaultOrderSeries: Int,
    val DefaultPagoRSeries: Int,
    val DefaultPriceList: Int,
    val DefaultProyecto: String,
    val DefaultSNSerieCli: Int,
    val DefaultSlpCode: Int,
    val DefaultTaxCode: String,
    val DefaultWarehouse: String,
    val Email: String,
    val IdPhone1: String,
    val IdPhone1Val: String,
    val Image: String,
    val Name: String,
    val Password: String,
    val Phone1: String,
    val ShowImage: String,
    val SuperUser: String,
    val CanApprove: String,
    val CanCreate: String,
    val CanDecline: String,
    val CanEditPrice: String,
    val CanUpdate: String
){
    constructor(): this(
        Code= "",
        Comment= "",
        DefaultCC1= "",
        DefaultCC2= "",
        DefaultCC3= "",
        DefaultCC4= "",
        DefaultCC5= "",
        DefaultCurrency= "",
        DefaultEmpId= 0,
        DefaultAcctCodeEf= "",
        DefaultAcctCodeTr= "",
        DefaultAcctCodeCh = "",
        DefaultAcctCodeDe = "",
        DefaultOrderSeries= 0,
        DefaultPagoRSeries= 0,
        DefaultPriceList= 0,
        DefaultProyecto= "",
        DefaultSNSerieCli= 0,
        DefaultSlpCode= 0,
        DefaultTaxCode= "",
        DefaultWarehouse= "",
        Email= "",
        IdPhone1= "",
        IdPhone1Val= "",
        Image= "",
        Name= "",
        Password= "",
        Phone1= "",
        ShowImage= "",
        SuperUser= "",
        CanApprove= "",
        CanCreate= "",
        CanDecline= "",
        CanEditPrice= "",
        CanUpdate= ""
    )
}

fun UsuarioEntity.toDomain() = DoUsuario(
    Code = Code,
    Comment = Comment,
    DefaultCC1 = DefaultCC1,
    DefaultCC2 = DefaultCC2,
    DefaultCC3 = DefaultCC3,
    DefaultCC4 = DefaultCC4,
    DefaultCC5 = DefaultCC5,
    DefaultCurrency = DefaultCurrency,
    DefaultEmpId = DefaultEmpId,
    DefaultAcctCodeEf = DefaultAcctCodeEf,
    DefaultAcctCodeTr = DefaultAcctCodeTr,
    DefaultAcctCodeCh = DefaultAcctCodeCh,
    DefaultAcctCodeDe = DefaultAcctCodeDe,
    DefaultOrderSeries = DefaultOrderSeries,
    DefaultPagoRSeries = DefaultPagoRSeries,
    DefaultPriceList = DefaultPriceList,
    DefaultProyecto = DefaultProyecto,
    DefaultSNSerieCli = DefaultSNSerieCli,
    DefaultSlpCode = DefaultSlpCode,
    DefaultTaxCode = DefaultTaxCode,
    DefaultWarehouse = DefaultWarehouse,
    Email = Email,
    IdPhone1 = IdPhone1,
    IdPhone1Val = IdPhone1Val,
    Image = Image,
    Name = Name,
    Password = Password,
    Phone1 = Phone1,
    ShowImage = ShowImage,
    SuperUser = SuperUser,
    CanApprove = CanApprove,
    CanCreate = CanCreate,
    CanDecline = CanDecline,
    CanEditPrice = CanEditPrice,
    CanUpdate = CanUpdate

)

fun Usuario.toDomain() = DoUsuario(
    Code = Code,
    Comment = Comment,
    DefaultCC1 = DefaultCC1,
    DefaultCC2 = DefaultCC2,
    DefaultCC3 = DefaultCC3,
    DefaultCC4 = DefaultCC4,
    DefaultCC5 = DefaultCC5,
    DefaultCurrency = DefaultCurrency,
    DefaultEmpId = DefaultEmpId,
    DefaultAcctCodeEf = DefaultAcctCodeEf,
    DefaultAcctCodeTr = DefaultAcctCodeTr,
    DefaultAcctCodeCh = DefaultAcctCodeCh,
    DefaultAcctCodeDe = DefaultAcctCodeDe,
    DefaultOrderSeries = DefaultOrderSeries,
    DefaultPagoRSeries = DefaultPagoRSeries,
    DefaultPriceList = DefaultPriceList,
    DefaultProyecto = DefaultProyecto,
    DefaultSNSerieCli = DefaultSNSerieCli,
    DefaultSlpCode = DefaultSlpCode,
    DefaultTaxCode = DefaultTaxCode,
    DefaultWarehouse = DefaultWarehouse,
    Email = Email,
    IdPhone1 = IdPhone1,
    IdPhone1Val = IdPhone1Val,
    Image = Image,
    Name = Name,
    Password = Password,
    Phone1 = Phone1,
    ShowImage = ShowImage,
    SuperUser = SuperUser,
    CanApprove = CanApprove,
    CanCreate = CanCreate,
    CanDecline = CanDecline,
    CanEditPrice = CanEditPrice,
    CanUpdate = CanUpdate
)

data class DoUsuarioView(
    val Codigo: String,
    val Password: String,
    val IdTelefono: String,
    val Nombre: String,
    val Correo: String,
    val Telefono: String,
    val Vendedor: String,
    val Zona: String,
    val ListaPrecio: String,
    val Impuesto: String,
    val Moneda: String,
    val Almacen: String,
    val SuperUser: String,
    val Activo: String,
    val SesionActiva: String,
    val EditarListaPrecios: String,
    val PuedeCrear: String,
    val PuedeActualizar: String,
    val PuedeDeclinar: String,
    val PuedeAprobar: String,
)